version: "3"
services:
  xxxxxxxxxxxxx:
    build: .
    container_name: xxxxxxxxxxxxx
    volumes:
      - "${HOME}/.m2:/root/.m2"
    environment:
      - "MYSQL_URL=${MYSQL_URL}"
      - "MYSQL_DB=${MYSQL_DB}"
      - "MYSQL_USERNAME=${MYSQL_USERNAME}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "PORT=${PORT}"
      - "JWT_SECRET=${JWT_SECRET}"
      - "JWT_EXPIRATION_DELAY=${JWT_EXPIRATION_DELAY}"
    network_mode: "host"