version: "3"
services:
  traefik:
    image: traefik:v2.4
    container_name: frogsoft-cms-traefik
    restart: unless-stopped
    networks:
      - frogsoft-cms-network
    command: 
      - --api
      - --entrypoints.web.address=:${TRAEFIK_ENTRYPOINT_PORT}
      - --providers.docker.exposedByDefault=false
    ports:
      - "${TRAEFIK_ENTRYPOINT_PORT}:${TRAEFIK_ENTRYPOINT_PORT}"
    volumes:
      # - .:/etc/traefik
      # - ./dynamic:/etc/traefik/dynamic
      # - ./certs:/etc/traefik/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true" # enable the dashboard
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_HOST}`)" # domain for dashboard
      - "traefik.http.routers.traefik.entrypoints=web"
      # - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal" # points to dashboard
      - "traefik.http.routers.traefik.middlewares=auth" # enable password auth
      - "traefik.http.middlewares.auth.basicauth.users=root:$$apr1$$qxlAutEf$$ztoeod7s4TgWQB8I1NAfW/"
      - "traefik.http.routers.traefik.middlewares=traefik-compress"
      - "traefik.http.middlewares.traefik-compress.compress=true"

  mysql:
    image: mysql:8.0.26
    container_name: frogsoft-cms-mysql
    volumes:
      - "./mysql/db_data:/var/lib/mysql"
      - "./mysql/conf.d:/etc/mysql/conf.d"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks: 
      frogsoft-cms-network:
        aliases:
          - mysql

  frogsoft-cms-backend:
    depends_on: 
      - mysql
    build: ./backend
    image: ${DOCKERHUB_USERNAME}/frogsoft-cms-backend:latest
    container_name: frogsoft-cms-backend
    restart: unless-stopped
    networks:
      - frogsoft-cms-network
    command:
      - "./wait-for-it.sh"
      - "mysql:3306"
      - "--"
      - "java"
      - "org.springframework.boot.loader.JarLauncher"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frogsoft-cms-backend.rule=Host(`${BACKEND_TRAEFIK_HOST}`)"
      - "traefik.http.routers.frogsoft-cms-backend.entrypoints=web"
      # - "traefik.http.routers.frogsoft-cms-backend.tls=true"
      - "traefik.http.services.frogsoft-cms-backend.loadbalancer.server.port=80"
      - "traefik.http.routers.frogsoft-cms-backend.middlewares=frogsoft-cms-backend-compress"
      - "traefik.http.middlewares.frogsoft-cms-backend-compress.compress=true"
    environment:
      MYSQL_URL: mysql
      MYSQL_DB: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PORT: 80
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_DELAY: ${JWT_EXPIRATION_DELAY}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    expose:
      - "80"


  frogsoft-cms-user:
    build: ./frontend-user
    image: ${DOCKERHUB_USERNAME}/frogsoft-cms-user:latest
    container_name: frogsoft-cms-user
    restart: unless-stopped
    networks:
      - frogsoft-cms-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frogsoft-cms-user.rule=Host(`${FRONTEND_USER_TRAEFIK_HOST}`)"
      - "traefik.http.routers.frogsoft-cms-user.entrypoints=web"
      # - "traefik.http.routers.frogsoft-cms-user.tls=true"
      - "traefik.http.services.frogsoft-cms-user.loadbalancer.server.port=80"
      - "traefik.http.routers.frogsoft-cms-user.middlewares=frogsoft-cms-user-compress"
      - "traefik.http.middlewares.frogsoft-cms-user-compress.compress=true"
    expose:
      - "80"

  frogsoft-cms-admin:
    build: ./frontend-admin
    image: ${DOCKERHUB_USERNAME}/frogsoft-cms-admin:latest
    container_name: frogsoft-cms-admin
    restart: unless-stopped
    # networks:
    #   - frogsoft-cms-network
    # network_mode: "host"
    environment: 
      VITE_BACKEND_URL: "${BACKEND_PORTOCOL}://${BACKEND_TRAEFIK_HOST}:${TRAEFIK_ENTRYPOINT_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frogsoft-cms-admin.rule=Host(`${FRONTEND_ADMIN_TRAEFIK_HOST}`)"
      - "traefik.http.routers.frogsoft-cms-admin.entrypoints=web"
      # - "traefik.http.routers.frogsoft-cms-admin.tls=true"
      - "traefik.http.services.frogsoft-cms-admin.loadbalancer.server.port=80"
      - "traefik.http.routers.frogsoft-cms-admin.middlewares=frogsoft-cms-admin-compress"
      - "traefik.http.middlewares.frogsoft-cms-admin-compress.compress=true"
    expose:
      - "80"
    ports: 
      - "10002:80"

networks:
  frogsoft-cms-network:
    name: frogsoft-cms-network